spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/information_system?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认60000（10分钟）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 18000000
      # 连接超时时间，默认30000
      connection-timeout: 3000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  redis:
    #    host: 192.168.92.128
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  session:
    store-type: redis
    timeout: 60
  #  rabbitmq:
  #    username: guest
  #    password: guest
  #    host: 127.0.0.1
  #    port: 5672
  ##    消息确认回调
  #    publisher-confirm-type: correlated
  ##  消息失败回调
  #    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决swaggerUI不匹配接口


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  path: files